name: online_store_application
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  json_annotation: ^4.8.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  extended_image: ^7.0.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  get_it: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:

  uses-material-design: true
  fonts:
    - family: Mark
      fonts:
        - asset: fonts/Mark-Pro.ttf
    - family: SfPro
      fonts:
        - asset: fonts/SF-Pro.ttf
  assets:
    - assets/images/no_image.png
       

